# ####################################################
# Configuration file for the fish detector

# Parameter values after the semi-columns can be
# modified as needed but section names and indentation
# shoud be kept as is.
# 
# Make sure there is a space between the : and the
# parameter value.
# ####################################################

ENVIRONMENT:
    sound_speed_mps: 1484

TDOA:
    ref_channel: 2
    upsample_res_sec: 0.0000001
    normalize: False

INVERSION:
    start_model: [0,0,0] 
    start_model_repeats: 5
    damping_factor: 0.2
    stop_delta_m: 0.01
    stop_max_iteration: 50


